apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tls-secret
spec:
  secretName: tls-secret
  dnsNames: # Replace these domains with your domains
  - ducltm-azurebootcamp.southeastasia.cloudapp.azure.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains: # Replace these domains with your domains
      - ducltm-azurebootcamp.southeastasia.cloudapp.azure.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
